name = "Natrium"
license = "MIT"
licenselink = "https://github.com/mobybit/hugo-natrium-theme/blob/master/LICENSE.md"
description = "Natrium minimal theme"
homepage = "https://github.com/mobybit/hugo-natrium-theme"
tags = ["blog", "minimal", "personal", "responsive"]
features = ["blog", "taxonomies", "privacy"]
min_version = 0.53

[author]
  name = "Neil Sabol"
  homepage = "https://blog.neilsabol.site"
  
[original]
  name = "Tim Krieger"
  homepage = "https://blog.mobybit.de"
  repo = "https://github.com/mobybit/hugo-natrium-theme"
